project:
  type: website
  output-dir: docs

website:
  title: "Peter Liu"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - ex_analysis.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-fold: true
    code-summary: "Show Code"
    page-layout: full
    
editor: visual

execute:
  freeze: auto



